//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GravityFormsAdapter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GravityFormsSQLEntities : DbContext
    {
        public GravityFormsSQLEntities()
            : base("name=GravityFormsSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGravityEntry> tblGravityEntries { get; set; }
        public virtual DbSet<tblGravityEntryValue> tblGravityEntryValues { get; set; }
        public virtual DbSet<tblGravityFieldInput> tblGravityFieldInputs { get; set; }
        public virtual DbSet<tblGravityField> tblGravityFields { get; set; }
        public virtual DbSet<tblGravityForm> tblGravityForms { get; set; }
    }
}
