//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GravityFormsAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGravityEntryValue
    {
        public int id { get; set; }
        public int entry_id { get; set; }
        public string entryKey { get; set; }
        public string entrySubKey { get; set; }
        public string entryValue { get; set; }
    }
}
