//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GravityFormsAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGravityEntry
    {
        public int id { get; set; }
        public int form_id { get; set; }
        public int created_by { get; set; }
        public string date_created { get; set; }
        public bool is_starred { get; set; }
        public bool is_read { get; set; }
        public string ip { get; set; }
        public string source_url { get; set; }
        public Nullable<int> post_id { get; set; }
        public string user_agent { get; set; }
        public string status { get; set; }
        public string currency { get; set; }
        public string payment_status { get; set; }
        public string payment_date { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public string transaction_id { get; set; }
        public Nullable<bool> is_fulfilled { get; set; }
        public Nullable<int> transaction_type { get; set; }
    }
}
